name: Check Lint

on: pull_request

jobs:
   Check_lint:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            elixir: ['1.16']
            otp: ['26']
      steps:
          - uses: actions/checkout@v2
          - uses: erlef/setup-elixir@v1
            with:
              elixir-version: ${{ matrix.elixir }}
              otp-version: ${{ matrix.otp }}
          - uses: actions/cache@v2
            id: mix-lint-cache
            with:
              path: ~/.mix
              key: ${{ runner.os }}-mix-${{ matrix.otp }}-${{ matrix.elixir }}-deps-${{ hashFiles(format('{0}-{1}', github.workspace, '/mix.lock')) }}
          - name: Install dependencies
            run: mix deps.get
          - name: Lint
            run: mix credo --strict